name: Format code with black

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
    
      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.12'
      
      - name: Install Black
        run: pip install black

      - name: Format with Black
        run: black .
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: format with black"
          branch: ${{ github.head_ref }}
